---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: waypoint-token-generator
  namespace: waypoint
  labels:
    app.kubernetes.io/name: waypoint
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: waypoint-token-generator
  namespace: waypoint
rules:
  - apiGroups: [""]
    resources: ["secrets"]
    verbs: ["create", "patch", "get", "watch", "list"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: waypoint-token-generator
  namespace: waypoint
  labels:
    app.kubernetes.io/name: waypoint
roleRef:
  apiGroup: "rbac.authorization.k8s.io"
  kind: Role
  name: waypoint-token-generator
subjects:
  - kind: ServiceAccount
    name: waypoint-token-generator
    namespace: waypoint
