#!/usr/bin/env bash

PWD="$( cd $(dirname $0)/.. && pwd)"

yq eval -i "select(.kind == \"Service\" and .metadata.labels[\"component\"] == \"ui\").spec.type |= \"NodePort\" |
            select(.kind == \"Service\" and .metadata.labels[\"component\"] == \"ui\").spec.ports = [
                    {\"name\": \"http\", \"port\": 80, \"targetPort\": \"http\" },
                    {\"name\": \"https\", \"port\": 443, \"nodePort\": 30003, \"targetPort\": \"https\"},
                    {\"name\": \"grpc\", \"port\": 9701, \"nodePort\": 30001, \"targetPort\": \"grpc\"},
                    {\"name\": \"https-2\", \"port\": 9702, \"nodePort\": 30002, \"targetPort\": \"https\"}
                  ]" ${PWD}/resources/waypoint-server.yaml

sh ${PWD}/scripts/inject-wcr
