---
apiVersion: batch/v1
kind: Job
metadata:
  name: waypoint-init-secret
  namespace: waypoint
  labels:
    app.kubernetes.io/name: waypoint
    app.kubernetes.io/instance: waypoint
spec:
  backoffLimit: 1
  activeDeadlineSeconds: 60
  ttlSecondsAfterFinished: 86400 # 24 hours
  template:
    metadata:
      name: waypoint-init-secret
      labels:
        app.kubernetes.io/name: waypoint
        app.kubernetes.io/instance: waypoint
    spec:
      serviceAccountName: waypoint-token-generator
      restartPolicy: Never
      containers:
        - name: server-token
          image: ghcr.io/syntasso/kratix-marketplace/waypoint-token-generator:v1
          imagePullPolicy: IfNotPresent
          command:
          - "kubectl"
          - "create"
          - "secret"
          - "generic"
          - "--from-literal=token="
          - "waypoint-server-token"
        - name: runner-token
          image: ghcr.io/syntasso/kratix-marketplace/waypoint-token-generator:v1
          imagePullPolicy: IfNotPresent
          command:
          - "kubectl"
          - "create"
          - "secret"
          - "generic"
          - "--from-literal=token="
          - "waypoint-runner-token"
