---
# Source: waypoint/templates/bootstrap-serviceaccount.yaml
apiVersion: v1
kind: ServiceAccount
metadata:
  name: waypoint-bootstrap
  namespace: waypoint
  labels:
    helm.sh/chart: waypoint-0.1.17
    app.kubernetes.io/name: waypoint
    app.kubernetes.io/instance: waypoint
    app.kubernetes.io/managed-by: Helm
---
# Source: waypoint/templates/runner-odr-serviceaccount.yaml
apiVersion: v1
kind: ServiceAccount
metadata:
  name: waypoint-runner-odr
  namespace: waypoint
  labels:
    helm.sh/chart: waypoint-0.1.17
    app.kubernetes.io/name: waypoint
    app.kubernetes.io/instance: waypoint
    app.kubernetes.io/managed-by: Helm
---
# Source: waypoint/templates/runner-serviceaccount.yaml
apiVersion: v1
kind: ServiceAccount
metadata:
  name: waypoint-runner
  namespace: waypoint
  labels:
    helm.sh/chart: waypoint-0.1.17
    app.kubernetes.io/name: waypoint
    app.kubernetes.io/instance: waypoint
    app.kubernetes.io/managed-by: Helm
---
# Source: waypoint/templates/server-serviceaccount.yaml
apiVersion: v1
kind: ServiceAccount
metadata:
  name: waypoint
  namespace: waypoint
  labels:
    helm.sh/chart: waypoint-0.1.17
    app.kubernetes.io/name: waypoint
    app.kubernetes.io/instance: waypoint
    app.kubernetes.io/managed-by: Helm
---
# Source: waypoint/templates/runner-odr-clusterrole.yaml
kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: waypoint-runner-odr
  labels:
    app.kubernetes.io/name: waypoint-runner-odr
    app.kubernetes.io/instance: waypoint
    app.kubernetes.io/managed-by: Helm
  namespace: waypoint
rules:
  - apiGroups: [""]
    resources: ["nodes"]
    verbs: ["get", "list"]
---
# Source: waypoint/templates/runner-odr-clusterrolebinding.yaml
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: waypoint-runner-odr-rolebinding-custom
  labels:
    app.kubernetes.io/name: waypoint-runner
    app.kubernetes.io/instance: waypoint
    app.kubernetes.io/managed-by: Helm
  namespace: waypoint
roleRef:
  apiGroup: ""
  kind: ClusterRole
  name: waypoint-runner-odr
subjects:
  - kind: ServiceAccount
    name: waypoint-runner-odr
    namespace: waypoint
---
# Source: waypoint/templates/bootstrap-role.yaml
kind: Role
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: waypoint-bootstrap
  labels:
    app.kubernetes.io/name: waypoint-bootstrap
    app.kubernetes.io/instance: waypoint
    app.kubernetes.io/managed-by: Helm
  namespace: waypoint
rules:
  - apiGroups: [""]
    resources: ["secrets"]
    verbs: ["get", "patch"]
  - apiGroups: [""]
    resources: ["services"]
    verbs: ["get"]
  - apiGroups: [""]
    resources: ["pods"]
    verbs: ["get"]
---
# Source: waypoint/templates/bootstrap-rolebinding.yaml
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: waypoint-bootstrap-rolebinding
  labels:
    app.kubernetes.io/name: waypoint-bootstrap
    app.kubernetes.io/instance: waypoint
    app.kubernetes.io/managed-by: Helm
  namespace: waypoint
roleRef:
  kind: Role
  name: waypoint-bootstrap
  apiGroup: rbac.authorization.k8s.io
subjects:
  - kind: ServiceAccount
    name: waypoint-bootstrap
    namespace: waypoint
---
# Source: waypoint/templates/runner-odr-rolebinding.yaml
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: waypoint-runner-odr-rolebinding-edit
  namespace: waypoint
  labels:
    app.kubernetes.io/name: waypoint-runner
    app.kubernetes.io/instance: waypoint
    app.kubernetes.io/managed-by: Helm
roleRef:
  apiGroup: ""
  kind: ClusterRole
  name: edit
subjects:
  - kind: ServiceAccount
    name: waypoint-runner-odr
    namespace: waypoint
---
# Source: waypoint/templates/runner-rolebinding.yaml
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: waypoint-runner-rolebinding
  labels:
    app.kubernetes.io/name: waypoint-runner
    app.kubernetes.io/instance: waypoint
    app.kubernetes.io/managed-by: Helm
  namespace: waypoint
roleRef:
  apiGroup: ""
  kind: ClusterRole
  name: edit
subjects:
  - kind: ServiceAccount
    name: waypoint-runner
    namespace: waypoint
---
# Source: waypoint/templates/server-service.yaml
# Headless service for Waypoint server statefulset.
apiVersion: v1
kind: Service
metadata:
  name: waypoint-server
  namespace: waypoint
  labels:
    helm.sh/chart: waypoint-0.1.17
    app.kubernetes.io/name: waypoint
    app.kubernetes.io/instance: waypoint
    app.kubernetes.io/managed-by: Helm
  annotations:
spec:
  clusterIP: None
  ports:
    - name: https
      port: 9702
      targetPort: https
    - name: grpc
      port: 9701
      targetPort: grpc
  selector:
    app.kubernetes.io/name: waypoint
    app.kubernetes.io/instance: waypoint
    component: server
---
# Source: waypoint/templates/ui-service.yaml
# UI Service for Waypoint Server
apiVersion: v1
kind: Service
metadata:
  name: waypoint-ui
  namespace: waypoint
  labels:
    app: waypoint
    chart: waypoint-0.1.17
    heritage: Helm
    release: waypoint
    component: ui
spec:
  selector:
    app.kubernetes.io/name: waypoint
    app.kubernetes.io/instance: waypoint
    component: server
  ports:
    - name: http
      port: 80
      targetPort: http
    - name: https
      port: 443
      targetPort: https
    - name: grpc
      port: 9701
      targetPort: grpc
    - name: https-2
      port: 9702
      targetPort: https
  type: LoadBalancer
---
# Source: waypoint/templates/runner-statefulset.yaml
# StatefulSet to run the Waypoint static runner.
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: waypoint-runner
  namespace: waypoint
  labels:
    app.kubernetes.io/name: waypoint
    app.kubernetes.io/instance: waypoint
    app.kubernetes.io/managed-by: Helm
spec:
  serviceName: waypoint-runner
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: waypoint
      app.kubernetes.io/instance: waypoint
      component: runner
  volumeClaimTemplates:
    - metadata:
        name: data-waypoint
      spec:
        accessModes:
          - ReadWriteOnce
        resources:
          requests:
            storage: 1Gi
  template:
    metadata:
      labels:
        helm.sh/chart: waypoint-0.1.17
        app.kubernetes.io/name: waypoint
        app.kubernetes.io/instance: waypoint
        component: runner
    spec:
      serviceAccountName: waypoint-runner
      securityContext:
        runAsNonRoot: true
        runAsUser: 100
        runAsGroup: 1000
        fsGroup: 1000
      volumes:
        - name: home
          emptyDir: {}
        - name: token
          secret:
            secretName: waypoint-runner-token
      initContainers:
        - name: wait-for-token
          image: "busybox"
          command:
            - /bin/sh
            - "-ec"
            - |
              until [ -s "/secret/token" ]; do
                echo "Waiting for runner token secret '/secret/token' to be populated from secret..."
                sleep 2
              done
          volumeMounts:
            - name: token
              mountPath: /secret
              readOnly: true
      containers:
        - name: waypoint
          resources:
            requests:
              cpu: 250m
              memory: 256Mi
          image: docker.io/hashicorp/waypoint:0.10.5
          imagePullPolicy: IfNotPresent
          command:
            - "waypoint"
          args:
            - "runner"
            - "agent"
            - "-liveness-tcp-addr=:1234"
            - "-state-dir=/data/runner"
            - "-vv"
          env:
            - name: HOME
              value: /home/waypoint
            - name: WAYPOINT_SERVER_ADDR
              value: waypoint-server:9701
            - name: WAYPOINT_SERVER_TLS
              value: "true"
            - name: WAYPOINT_SERVER_TLS_SKIP_VERIFY
              value: "true"
            - name: WAYPOINT_SERVER_TOKEN
              valueFrom:
                secretKeyRef:
                  name: waypoint-runner-token
                  key: token
          volumeMounts:
            - name: home
              mountPath: /home/waypoint
            - name: data-waypoint
              mountPath: /data
          livenessProbe:
            tcpSocket:
              port: 1234
            failureThreshold: 10
            initialDelaySeconds: 5
            periodSeconds: 3
            successThreshold: 1
            timeoutSeconds: 5
---
# Source: waypoint/templates/server-statefulset.yaml
# StatefulSet to run the Waypoint server.
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: waypoint-server
  namespace: waypoint
  labels:
    app.kubernetes.io/name: waypoint
    app.kubernetes.io/instance: waypoint
    app.kubernetes.io/managed-by: Helm
spec:
  serviceName: waypoint-server
  replicas: 1 # Waypoint doesn't support horizontal scaling today
  selector:
    matchLabels:
      app.kubernetes.io/name: waypoint
      app.kubernetes.io/instance: waypoint
      component: server
  template:
    metadata:
      labels:
        helm.sh/chart: waypoint-0.1.17
        app.kubernetes.io/name: waypoint
        app.kubernetes.io/instance: waypoint
        component: server
    spec:
      terminationGracePeriodSeconds: 30
      serviceAccountName: waypoint
      securityContext:
        runAsNonRoot: true
        runAsUser: 100
        runAsGroup: 1000
        fsGroup: 1000
      volumes:
        - name: home
          emptyDir: {}
      containers:
        - name: waypoint
          resources:
            requests:
              cpu: 250m
              memory: 256Mi
          image: docker.io/hashicorp/waypoint:0.10.5
          imagePullPolicy: IfNotPresent
          command:
            - "waypoint"
          args:
            - "server"
            - "run"
            - "-accept-tos"
            - "-db=/data/data.db"
            - "-listen-grpc=0.0.0.0:9701"
            - "-listen-http=0.0.0.0:9702"
            - "-listen-http-insecure=0.0.0.0:9703"
            - "-vv"
          env:
            - name: HOME
              value: /home/waypoint
          volumeMounts:
            - name: data-waypoint
              mountPath: /data
            - name: home
              mountPath: /home/waypoint
          ports:
            - containerPort: 9701
              name: grpc
            - containerPort: 9702
              name: https
            - containerPort: 9703
              name: http
          livenessProbe:
            tcpSocket:
              port: grpc
            failureThreshold: 2
            initialDelaySeconds: 5
            periodSeconds: 3
            successThreshold: 1
            timeoutSeconds: 5
  volumeClaimTemplates:
    - metadata:
        name: data-waypoint
      spec:
        accessModes:
          - ReadWriteOnce
        resources:
          requests:
            storage: 10Gi
---
# Source: waypoint/templates/bootstrap-job.yaml
apiVersion: batch/v1
kind: Job
metadata:
  name: waypoint-bootstrap-0.10.5-bnvsni
  namespace: waypoint
  labels:
    app.kubernetes.io/name: waypoint
    app.kubernetes.io/instance: waypoint
    app.kubernetes.io/managed-by: Helm
    helm.sh/chart: waypoint-0.1.17
spec:
  backoffLimit: 1
  activeDeadlineSeconds: 600
  ttlSecondsAfterFinished: 300
  template:
    metadata:
      name: waypoint-bootstrap
      labels:
        helm.sh/chart: waypoint-0.1.17
        app.kubernetes.io/name: waypoint
        app.kubernetes.io/instance: waypoint
        component: bootstrap
    spec:
      serviceAccountName: waypoint-bootstrap
      restartPolicy: Never
      securityContext:
        runAsNonRoot: true
        runAsUser: 100
        runAsGroup: 1000
        fsGroup: 1000
      volumes:
        - name: home
          emptyDir: {}
      containers:
        - name: waypoint-bootstrap
          resources:
          image: docker.io/hashicorp/waypoint:0.10.5
          imagePullPolicy: IfNotPresent
          command:
            - "waypoint"
          args:
            - "k8s"
            - "bootstrap"
            - "-vvv"
            - "-root-token-secret=waypoint-server-token"
            - "-runner-token-secret=waypoint-runner-token"
            - "-odr-image=docker.io/hashicorp/waypoint-odr:0.10.5"
            - "-odr-service-account=waypoint-runner-odr"
            - "-odr-image-pull-policy=IfNotPresent"
            - "-advertise-service=waypoint-ui"
            - "-advertise-tls=true"
            - "-advertise-tls-skip-verify=true"
          env:
            - name: HOME
              value: /home/waypoint
            - name: WAYPOINT_SERVER_ADDR
              value: waypoint-server:9701
            - name: WAYPOINT_SERVER_TLS
              value: "true"
            - name: WAYPOINT_SERVER_TLS_SKIP_VERIFY
              value: "true"
          volumeMounts:
            - name: home
              mountPath: /home
